# Generated by Django 3.2.16 on 2025-10-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Заметки', 'verbose_name_plural': 'Заметки'},
        ),
    ]
